<script setup lang="ts">
useHead({ title: 'FAQ' })
useSeoMeta({
    description: 'Frequently asked questions about EVE-KILL — how killmails work, item pricing, our API, donations, privacy policy, and more.',
    ogTitle: 'FAQ — EVE-KILL',
    ogDescription: 'Answers to common questions about EVE-KILL, killmails, pricing, and our API.',
})

const items = [
    { key: 'killmail', label: 'What is a killmail?', icon: 'lucide:file-text', content: 'A Killmail is a comprehensive data record generated by EVE Online whenever a ship is destroyed in combat. This detailed report captures essential information including the victim\'s identity, all participating attackers, destroyed and dropped items, damage statistics, and precise location details — providing a complete picture of the engagement.' },
    { key: 'killmails', label: 'How are kills processed?', icon: 'lucide:mail', content: 'Our advanced queueing system processes killmails with maximum efficiency, prioritizing speed and accuracy. Once processed, killmails are instantly broadcast via websockets for real-time display on the site, ensuring you always have the latest combat data. All processed killmails are simultaneously made available through our comprehensive API for developers and third-party applications.' },
    { key: 'pricing', label: 'How are item prices calculated?', icon: 'lucide:dollar-sign', content: 'Item prices are updated daily from the Forge region market (Jita). When a killmail is processed, it uses the most recent snapshot available at that time. Because the EVE market fluctuates constantly, prices shown on older killmails may not always match the current market value. This ensures consistent and fair valuations across all records.' },
    { key: 'api', label: 'Do you offer an API?', icon: 'lucide:code', content: 'Yes, we offer a robust and well-documented API that provides programmatic access to our extensive killmail database and analytics. Developers can access comprehensive endpoints for killmails, statistics, and related game data, enabling seamless integration with third-party tools and applications.' },
    { key: 'donations', label: 'Donations?', icon: 'lucide:heart', content: 'Yes, we welcome contributions through our <a href="/donate">Support page</a> for those who wish to help sustain and enhance our services. While donations are entirely optional and will never be required to access our platform, they directly support ongoing development, server costs, and new features. We sincerely appreciate any level of support from our community.' },
    { key: 'ads', label: 'Ads? Tracking?', icon: 'lucide:ban', content: 'We are firmly committed to providing a clean, distraction-free experience. Our platform will never feature intrusive advertisements or implement user tracking systems. We believe in respecting your privacy and maintaining the integrity of our service without compromising the user experience through advertising.' },
    { key: 'account', label: 'Do I need an account?', icon: 'lucide:user', content: 'No, you don\'t need an account to access and browse our comprehensive killboard data. However, creating an account unlocks enhanced features such as posting comments, creating campaigns, and personalizing your experience. When logging in through EVE SSO, you maintain full control over which permissions you grant — we operate on a principle of minimal necessary access.' },
    { key: 'contact', label: 'How can I contact support?', icon: 'lucide:message-square', content: 'Our support team is readily accessible through our active <a href="https://discord.gg/Bz5gMHd" target="_blank" rel="noopener noreferrer">Discord community</a>, where you can engage directly with both our team and fellow users. For technical inquiries, feature requests, or bug reports, our <a href="https://github.com/EVE-KILL" target="_blank" rel="noopener noreferrer">GitHub repository</a> provides a structured platform for detailed discussions and issue tracking.' },
]

// Strip HTML tags for schema.org plain-text answers
const stripHtml = (html: string) => html.replace(/<[^>]*>/g, '')

useSchemaOrg([
    defineWebPage({ '@type': 'FAQPage' }),
    ...items.map(item => ({
        '@type': 'Question' as const,
        'name': item.label,
        'acceptedAnswer': {
            '@type': 'Answer' as const,
            'text': stripHtml(item.content),
        },
    })),
])

const openItem = ref<string | null>(null)
const toggle = (key: string) => {
    openItem.value = openItem.value === key ? null : key
}
</script>

<template>
    <InfoPage
        title="Frequently Asked Questions"
        subtitle="How killmails get here, where prices come from, and what the API will and won't do."
        icon="lucide:circle-help"
    >
        <div class="glass-panel p-2">
            <div class="divide-y divide-gray-700/50 rounded-lg">
                <div v-for="item in items" :key="item.key" class="last:border-b-0">
                    <button
                        class="w-full flex items-center justify-between py-5 px-3 text-left hover:bg-white/[0.02] transition-colors"
                        @click="toggle(item.key)">
                        <div class="flex items-center gap-3">
                            <Icon :name="item.icon" class="w-5 h-5 text-blue-400 flex-shrink-0" />
                            <span class="text-lg font-medium text-white">{{ item.label }}</span>
                        </div>
                        <Icon :name="openItem === item.key ? 'lucide:chevron-up' : 'lucide:chevron-down'"
                            class="w-5 h-5 text-gray-500 flex-shrink-0 transition-transform duration-200" />
                    </button>
                    <div v-show="openItem === item.key" class="pb-5 px-3 pl-11 text-gray-300 leading-relaxed faq-content" v-html="item.content"></div>
                </div>
            </div>
        </div>
    </InfoPage>
</template>

<style scoped>
.faq-content :deep(a) {
    color: var(--color-brand-primary);
    text-decoration: none;
    font-weight: 500;
    transition: all 0.2s ease;
}
.faq-content :deep(a:hover) {
    text-decoration: underline;
    opacity: 0.9;
}
</style>
