<script setup lang="ts">
/**
 * The share-link text that follows the top curve of the ring via
 * SVG `<textPath>`. Ported from @eveshipfit/react's FitLink.tsx.
 *
 * The click-to-copy behavior is intentionally stubbed for now — the
 * ESF v3 fit encoder (gzip + base64 round-trip) hasn't been ported
 * yet. Once the encoder lands, swap `onShareClick` to actually build
 * the shareable URL and copy it to the clipboard.
 *
 * We still render the curved text so the ring's visual composition
 * matches the reference. The underlying `<path id="fitlink">` is
 * required — `textPath` references it by id.
 */

const props = defineProps<{
    isPreview?: boolean;
}>();

const route = useRoute();
const copied = ref(false);

const linkText = computed(() => {
    if (copied.value) return "copied to clipboard";
    if (props.isPreview) return "generated by evekill";
    return "share fit";
});

async function onShareClick(e: MouseEvent) {
    e.preventDefault();
    // TODO: wire to ESF v3 encoder once ported (task #42). For now just
    // flash the copied indicator so the UI state is visible.
    if (!navigator.clipboard) return;
    try {
        await navigator.clipboard.writeText(window.location.href);
        copied.value = true;
        setTimeout(() => (copied.value = false), 2000);
    } catch {
        /* clipboard denied — quietly no-op */
    }
}

import styles from "./ShipFit.module.css";
</script>

<template>
    <div :class="styles.fitLink">
        <svg viewBox="0 0 730 730" xmlns="http://www.w3.org/2000/svg">
            <path id="fitlink" fill="none" d="M18,365 A25,25 0 0,1 712,365" />

            <a :href="route.fullPath" @click="onShareClick">
                <text text-anchor="middle">
                    <textPath start-offset="50%" href="#fitlink" fill="#cdcdcd">{{ linkText }}</textPath>
                </text>
            </a>
        </svg>
    </div>
</template>
