package killmail

import (
	"context"
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/eve-kill/shrike/internal/eve"
)

// A hundred and six real killmails, fetched from ESI and committed under
// testdata/, spanning the shapes that actually break a parser: freighters with
// containers nested inside containers, capitals whose hulls have no market
// price, pods worth ten thousand ISK by convention, rat kills with no player on
// them at all, fleet fights with two hundred attackers, and mails from 2008 whose
// modules no longer exist.
//
// The static data they need — types, groups, systems, dogma, and the Jita price
// of every item as of the day it died — is committed alongside them in sde.json,
// generated by scripts/build-killmail-fixture.py. That is what makes these tests
// runnable anywhere: no database, no network, no SDE import.

const (
	corpusDir      = "testdata/corpus"
	manifestPath   = "testdata/corpus.json"
	sdeFixturePath = "testdata/sde.json"
)

// fixture is the shape of sde.json.
type fixture struct {
	Types map[string]struct {
		GroupID               int32  `json:"group_id"`
		CategoryID            int32  `json:"category_id"`
		Name                  string `json:"name"`
		VariationParentTypeID int32  `json:"variation_parent_type_id"`
		MetaGroupID           int32  `json:"meta_group_id"`
		MarketGroupID         int32  `json:"market_group_id"`
	} `json:"types"`
	Groups map[string]struct {
		CategoryID int32  `json:"category_id"`
		Name       string `json:"name"`
	} `json:"groups"`
	Systems map[string]struct {
		ConstellationID int32   `json:"constellation_id"`
		RegionID        int32   `json:"region_id"`
		Name            string  `json:"name"`
		Security        float64 `json:"security"`
	} `json:"systems"`
	Regions map[string]struct {
		Name string `json:"name"`
	} `json:"regions"`
	Constellations map[string]struct {
		Name     string `json:"name"`
		RegionID int32  `json:"region_id"`
	} `json:"constellations"`
	Dogma        map[string]float64            `json:"dogma"`
	CustomPrices map[string]float64            `json:"custom_prices"`
	Prices       map[string]map[string]float64 `json:"prices"`
}

func loadFixture(t testing.TB) (*eve.Cache, *fixture) {
	t.Helper()

	raw, err := os.ReadFile(sdeFixturePath)
	if err != nil {
		t.Fatalf("read fixture: %v (regenerate with scripts/build-killmail-fixture.py)", err)
	}
	var f fixture
	if err := json.Unmarshal(raw, &f); err != nil {
		t.Fatalf("parse fixture: %v", err)
	}

	data := eve.CacheData{
		Types:          map[int32]eve.Type{},
		Groups:         map[int32]eve.Group{},
		Systems:        map[int32]eve.System{},
		Regions:        map[int32]eve.Region{},
		Constellations: map[int32]eve.Constellation{},
		Dogma:          map[eve.DogmaKey]float64{},
		CustomPrices:   map[int32]float64{},
	}
	for id, v := range f.Types {
		data.Types[atoi32(t, id)] = eve.Type{
			GroupID: v.GroupID, CategoryID: v.CategoryID, Name: v.Name,
			VariationParentTypeID: v.VariationParentTypeID,
			MetaGroupID:           v.MetaGroupID, MarketGroupID: v.MarketGroupID,
		}
	}
	for id, v := range f.Groups {
		data.Groups[atoi32(t, id)] = eve.Group{CategoryID: v.CategoryID, Name: v.Name}
	}
	for id, v := range f.Systems {
		data.Systems[atoi32(t, id)] = eve.System{
			ConstellationID: v.ConstellationID, RegionID: v.RegionID,
			Name: v.Name, Security: v.Security,
		}
	}
	for id, v := range f.Regions {
		data.Regions[atoi32(t, id)] = eve.Region{Name: v.Name}
	}
	for id, v := range f.Constellations {
		data.Constellations[atoi32(t, id)] = eve.Constellation{Name: v.Name, RegionID: v.RegionID}
	}
	for key, value := range f.Dogma {
		typeID, attrID, ok := strings.Cut(key, ":")
		if !ok {
			t.Fatalf("malformed dogma key %q", key)
		}
		data.Dogma[eve.DogmaKey{TypeID: atoi32(t, typeID), AttributeID: atoi32(t, attrID)}] = value
	}
	for id, v := range f.CustomPrices {
		data.CustomPrices[atoi32(t, id)] = v
	}

	return eve.NewCache(data), &f
}

// pricesFor builds a resolver seeded with the day's snapshot, so no database is
// consulted and the price of every type is exactly what it was on the day.
func (f *fixture) pricesFor(t testing.TB, cache *eve.Cache, date string) *eve.Prices {
	t.Helper()
	market := map[int32]float64{}
	for id, v := range f.Prices[date] {
		market[atoi32(t, id)] = v
	}
	p := eve.NewPrices(nil, cache)
	p.Seed(date, market)
	return p
}

func atoi32(t testing.TB, s string) int32 {
	t.Helper()
	n, err := strconv.ParseInt(s, 10, 32)
	if err != nil {
		t.Fatalf("bad numeric key %q: %v", s, err)
	}
	return int32(n)
}

type corpusEntry struct {
	id   int64
	kind string
	esi  ESIKillmail
	raw  []byte
}

func loadCorpus(t testing.TB) []corpusEntry {
	t.Helper()

	manifestRaw, err := os.ReadFile(manifestPath)
	if err != nil {
		t.Fatalf("read manifest: %v", err)
	}
	var manifest map[string]string
	if err := json.Unmarshal(manifestRaw, &manifest); err != nil {
		t.Fatalf("parse manifest: %v", err)
	}

	files, err := filepath.Glob(filepath.Join(corpusDir, "*.json"))
	if err != nil {
		t.Fatal(err)
	}
	if len(files) == 0 {
		t.Fatalf("no killmails in %s", corpusDir)
	}

	out := make([]corpusEntry, 0, len(files))
	for _, path := range files {
		raw, err := os.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		var km ESIKillmail
		if err := json.Unmarshal(raw, &km); err != nil {
			t.Fatalf("%s: %v", path, err)
		}
		id := strings.TrimSuffix(filepath.Base(path), ".json")
		if strconv.FormatInt(km.KillmailID, 10) != id {
			t.Fatalf("%s holds killmail %d", path, km.KillmailID)
		}
		out = append(out, corpusEntry{id: km.KillmailID, kind: manifest[id], esi: km, raw: raw})
	}
	return out
}

var (
	benchmarkDecoded ESIKillmail
	benchmarkParsed  *Parsed
)

func BenchmarkDecodeESIKillmail(b *testing.B) {
	entries := loadCorpus(b)
	largest := entries[0]
	for _, entry := range entries[1:] {
		if len(entry.raw) > len(largest.raw) {
			largest = entry
		}
	}

	b.ReportAllocs()
	b.SetBytes(int64(len(largest.raw)))
	b.ResetTimer()
	for b.Loop() {
		var decoded ESIKillmail
		if err := json.Unmarshal(largest.raw, &decoded); err != nil {
			b.Fatal(err)
		}
		benchmarkDecoded = decoded
	}
}

func BenchmarkParseESIKillmail(b *testing.B) {
	cache, fixture := loadFixture(b)
	entries := loadCorpus(b)
	largest := entries[0]
	for _, entry := range entries[1:] {
		if len(entry.raw) > len(largest.raw) {
			largest = entry
		}
	}
	date := largest.esi.KillmailTime.UTC().Format("2006-01-02")
	prices := fixture.pricesFor(b, cache, date)
	ctx := context.Background()

	b.ReportAllocs()
	b.ResetTimer()
	for b.Loop() {
		parsed, err := Parse(ctx, cache, prices, &largest.esi, largest.esi.KillmailHash, 0)
		if err != nil {
			b.Fatal(err)
		}
		benchmarkParsed = parsed
	}
}

// countESIItems walks the raw tree, which is the independent count the parser's
// flattening is checked against.
func countESIItems(items []ESIItem) int {
	n := 0
	for _, item := range items {
		n++
		n += countESIItems(item.Items)
	}
	return n
}

// Every mail in the corpus must parse into rows that are internally consistent.
// These are the invariants that hold for any killmail, whatever it is.
func TestCorpusParsesConsistently(t *testing.T) {
	cache, f := loadFixture(t)
	ctx := context.Background()

	for _, entry := range loadCorpus(t) {
		t.Run(strconv.FormatInt(entry.id, 10)+"-"+entry.kind, func(t *testing.T) {
			date := entry.esi.KillmailTime.UTC().Format("2006-01-02")
			prices := f.pricesFor(t, cache, date)

			parsed, err := Parse(ctx, cache, prices, &entry.esi, entry.esi.KillmailHash, 0)
			if err != nil {
				t.Fatalf("parse: %v", err)
			}
			km := parsed.Killmail

			if km.KillmailID != entry.id {
				t.Errorf("killmail_id = %d, want %d", km.KillmailID, entry.id)
			}
			if km.KillmailHash == "" {
				t.Error("killmail_hash was not carried through")
			}
			if km.KillmailTime.IsZero() {
				t.Error("killmail_time is zero")
			}
			if km.SolarSystemID == 0 {
				t.Error("solar_system_id is unset")
			}

			// A known system must resolve to its constellation and region;
			// otherwise every regional statistic silently loses this kill.
			if sys, ok := cache.System(km.SolarSystemID); ok {
				if km.RegionID != sys.RegionID {
					t.Errorf("region_id = %d, want %d", km.RegionID, sys.RegionID)
				}
				if km.ConstellationID != sys.ConstellationID {
					t.Errorf("constellation_id = %d, want %d", km.ConstellationID, sys.ConstellationID)
				}
			}

			// Attackers: one row each, in ESI order, indices dense from zero.
			if len(parsed.Attackers) != len(entry.esi.Attackers) {
				t.Fatalf("%d attacker rows for %d ESI attackers", len(parsed.Attackers), len(entry.esi.Attackers))
			}
			if km.AttackerCount != int32(len(entry.esi.Attackers)) {
				t.Errorf("attacker_count = %d, want %d", km.AttackerCount, len(entry.esi.Attackers))
			}
			finalBlows := 0
			for i, a := range parsed.Attackers {
				if a.AttackerIndex != int32(i) {
					t.Errorf("attacker %d has index %d", i, a.AttackerIndex)
				}
				if a.KillmailID != entry.id {
					t.Errorf("attacker %d has killmail_id %d", i, a.KillmailID)
				}
				if !a.KillmailTime.Equal(km.KillmailTime) {
					t.Errorf("attacker %d has a different killmail_time", i)
				}
				if a.FinalBlow {
					finalBlows++
				}
				// A resolved hull must carry its group, or ship-class stats
				// silently drop the row.
				if a.ShipTypeID != 0 {
					if ty, ok := cache.Type(a.ShipTypeID); ok && ty.GroupID != a.ShipGroupID {
						t.Errorf("attacker %d ship group = %d, want %d", i, a.ShipGroupID, ty.GroupID)
					}
				}
			}
			if len(parsed.Attackers) > 0 && finalBlows > 1 {
				t.Errorf("%d attackers claim the final blow", finalBlows)
			}

			// Items: the flattened tree, indices dense, parents pointing back.
			wantItems := countESIItems(entry.esi.Victim.Items)
			if len(parsed.Items) != wantItems {
				t.Fatalf("%d item rows for %d items in the ESI tree", len(parsed.Items), wantItems)
			}
			for i, it := range parsed.Items {
				if it.ItemIndex != int32(i) {
					t.Errorf("item %d has index %d", i, it.ItemIndex)
				}
				if it.KillmailID != entry.id {
					t.Errorf("item %d has killmail_id %d", i, it.KillmailID)
				}
				if it.TypeID == 0 {
					t.Errorf("item %d has no type", i)
				}
				// A parent must be an earlier item, which only holds if the
				// walk is depth-first — and is what makes the column usable.
				if it.ParentIndex != NoParent && it.ParentIndex >= it.ItemIndex {
					t.Errorf("item %d points forward to parent %d", i, it.ParentIndex)
				}
				if it.QuantityDropped < 0 || it.QuantityDestroyed < 0 {
					t.Errorf("item %d has a negative quantity", i)
				}
			}

			// Values.
			for name, v := range map[string]float64{
				"total": km.TotalValue, "fitted": km.FittedValue,
				"dropped": km.DroppedValue, "destroyed": km.DestroyedValue,
			} {
				if v < 0 {
					t.Errorf("%s_value is negative: %v", name, v)
				}
				if math.IsNaN(v) || math.IsInf(v, 0) {
					t.Errorf("%s_value is not a number: %v", name, v)
				}
			}
			// Everything destroyed or dropped is part of the total, and the
			// fitted subset cannot exceed it.
			if km.FittedValue > km.TotalValue+0.001 {
				t.Errorf("fitted_value %v exceeds total_value %v", km.FittedValue, km.TotalValue)
			}
			if km.DroppedValue+km.DestroyedValue > km.TotalValue+0.001 {
				t.Errorf("dropped+destroyed %v exceeds total_value %v",
					km.DroppedValue+km.DestroyedValue, km.TotalValue)
			}
			// A ship that died is worth something. Zero here means a price
			// lookup silently failed.
			if km.VictimShipTypeID != 0 && km.TotalValue <= 0 {
				t.Errorf("a kill with a ship has total_value %v", km.TotalValue)
			}

			if km.Points < 1 {
				t.Errorf("points = %d, below the floor of 1", km.Points)
			}
			if km.VictimShipTypeID != 0 {
				if ty, ok := cache.Type(km.VictimShipTypeID); ok && ty.GroupID != km.VictimShipGroupID {
					t.Errorf("victim ship group = %d, want %d", km.VictimShipGroupID, ty.GroupID)
				}
			}
			if km.Blob {
				t.Error("blob is set by nothing yet and must stay false")
			}
		})
	}
}

// Parsing is a pure function of its inputs. If it is not, a killmail reprocessed
// after a restart quietly disagrees with the row already stored.
func TestCorpusParseIsDeterministic(t *testing.T) {
	cache, f := loadFixture(t)
	ctx := context.Background()

	for _, entry := range loadCorpus(t) {
		date := entry.esi.KillmailTime.UTC().Format("2006-01-02")

		first, err := Parse(ctx, cache, f.pricesFor(t, cache, date), &entry.esi, entry.esi.KillmailHash, 0)
		if err != nil {
			t.Fatalf("%d: %v", entry.id, err)
		}
		second, err := Parse(ctx, cache, f.pricesFor(t, cache, date), &entry.esi, entry.esi.KillmailHash, 0)
		if err != nil {
			t.Fatalf("%d: %v", entry.id, err)
		}

		if diffs := Diff(first, second, 0); len(diffs) != 0 {
			t.Errorf("killmail %d parsed differently twice: %v", entry.id, diffs[:min(3, len(diffs))])
		}
	}
}

// Each category was chosen because it exercises something specific. These are
// the assertions that would not hold for an arbitrary mail.
func TestCorpusCategoryExpectations(t *testing.T) {
	cache, f := loadFixture(t)
	ctx := context.Background()

	seen := map[string]int{}
	for _, entry := range loadCorpus(t) {
		date := entry.esi.KillmailTime.UTC().Format("2006-01-02")
		parsed, err := Parse(ctx, cache, f.pricesFor(t, cache, date), &entry.esi, entry.esi.KillmailHash, 0)
		if err != nil {
			t.Fatalf("%d: %v", entry.id, err)
		}
		km := parsed.Killmail
		seen[entry.kind]++

		switch entry.kind {
		case "pod":
			// Pods are priced by convention at 10k, never by market.
			if km.VictimShipGroupID != 29 {
				t.Errorf("%d: pod has ship group %d", entry.id, km.VictimShipGroupID)
			}

		case "npc":
			if !km.IsNPC {
				t.Errorf("%d: a rat kill was not flagged is_npc", entry.id)
			}
			for i, a := range parsed.Attackers {
				if a.CharacterID != 0 {
					t.Errorf("%d: attacker %d on an NPC kill has a character", entry.id, i)
				}
			}

		case "solo":
			if !km.IsSolo {
				t.Errorf("%d: a solo kill was not flagged is_solo", entry.id)
			}
			players := 0
			for _, a := range parsed.Attackers {
				if a.CharacterID != 0 {
					players++
				}
			}
			if players != 1 {
				t.Errorf("%d: is_solo with %d player attackers", entry.id, players)
			}

		case "no_items":
			if len(parsed.Items) != 0 {
				t.Errorf("%d: expected an empty hold, got %d items", entry.id, len(parsed.Items))
			}

		case "nested_items":
			nested := 0
			for _, it := range parsed.Items {
				if it.ParentIndex != NoParent {
					nested++
				}
			}
			if nested == 0 {
				t.Errorf("%d: no nested items survived flattening", entry.id)
			}

		case "blueprint_copy":
			copies := 0
			for _, it := range parsed.Items {
				if it.Singleton == SingletonBPC {
					copies++
				}
			}
			if copies == 0 {
				t.Errorf("%d: no blueprint copies in a mail chosen for carrying them", entry.id)
			}

		case "freighter":
			if km.VictimShipGroupID != 513 && km.VictimShipGroupID != 902 {
				t.Errorf("%d: freighter has ship group %d", entry.id, km.VictimShipGroupID)
			}

		case "supercapital":
			if km.VictimShipGroupID != 30 && km.VictimShipGroupID != 659 {
				t.Errorf("%d: supercapital has ship group %d", entry.id, km.VictimShipGroupID)
			}
			// These hulls never trade; their value comes from custom_prices.
			// A market-priced titan would read as worth almost nothing.
			if km.TotalValue < 1e9 {
				t.Errorf("%d: supercapital valued at %.0f ISK — the custom price did not apply",
					entry.id, km.TotalValue)
			}

		case "blob":
			if km.AttackerCount <= 50 {
				t.Errorf("%d: expected a blob, got %d attackers", entry.id, km.AttackerCount)
			}
			if km.IsSolo {
				t.Errorf("%d: a %d-attacker kill was flagged solo", entry.id, km.AttackerCount)
			}

		case "structure":
			if ty, ok := cache.Type(km.VictimShipTypeID); ok && ty.CategoryID != 65 {
				t.Errorf("%d: structure kill has victim category %d", entry.id, ty.CategoryID)
			}
		}
	}

	// The corpus is only worth what it covers, so a category quietly emptying
	// out has to fail rather than pass vacuously.
	for _, kind := range []string{
		"pod", "npc", "solo", "no_items", "nested_items", "blueprint_copy",
		"freighter", "supercapital", "blob", "structure", "battleship",
		"capital", "ancient", "war", "t3cruiser", "mining", "industrial",
		"frigate", "faction_mods", "recent",
	} {
		if seen[kind] == 0 {
			t.Errorf("the corpus no longer covers %q", kind)
		}
	}
	t.Logf("corpus: %d killmails across %d categories", len(loadCorpus(t)), len(seen))
}

// Blueprint copies carry no market value whatever the original sells for.
// Without the rule, a hauler full of copied battleship blueprints reads as a
// fortune.
func TestCorpusBlueprintCopiesArePricedAtTheFloor(t *testing.T) {
	cache, f := loadFixture(t)
	ctx := context.Background()

	checked := 0
	for _, entry := range loadCorpus(t) {
		if entry.kind != "blueprint_copy" {
			continue
		}
		date := entry.esi.KillmailTime.UTC().Format("2006-01-02")
		prices := f.pricesFor(t, cache, date)

		parsed, err := Parse(ctx, cache, prices, &entry.esi, entry.esi.KillmailHash, 0)
		if err != nil {
			t.Fatal(err)
		}

		// Value the same mail with every copy flipped to an original; the
		// difference proves the rule is doing something.
		flipped := entry.esi
		flipped.Victim.Items = unsetSingleton(entry.esi.Victim.Items)
		alt, err := Parse(ctx, cache, f.pricesFor(t, cache, date), &flipped, entry.esi.KillmailHash, 0)
		if err != nil {
			t.Fatal(err)
		}

		if alt.Killmail.TotalValue < parsed.Killmail.TotalValue {
			t.Errorf("%d: treating copies as originals lowered the value (%v → %v)",
				entry.id, parsed.Killmail.TotalValue, alt.Killmail.TotalValue)
		}
		checked++
	}
	if checked == 0 {
		t.Fatal("no blueprint-copy mails in the corpus")
	}
}

func unsetSingleton(items []ESIItem) []ESIItem {
	out := make([]ESIItem, len(items))
	for i, it := range items {
		out[i] = it
		if out[i].Singleton == SingletonBPC {
			out[i].Singleton = 0
		}
		out[i].Items = unsetSingleton(it.Items)
	}
	return out
}

// A fixture regenerated with the wrong date logic would still parse — every
// price would just quietly fall to the 0.01 floor and every value would be
// wrong by orders of magnitude. Nothing else in this file would notice, because
// a floored value is still positive, still consistent, and still deterministic.
//
// So the corpus asserts that prices actually resolved.
func TestCorpusPricesResolve(t *testing.T) {
	cache, f := loadFixture(t)
	ctx := context.Background()

	hulls, hullsAtFloor := 0, 0
	items, itemsAtFloor := 0, 0
	var total float64

	for _, entry := range loadCorpus(t) {
		date := entry.esi.KillmailTime.UTC().Format("2006-01-02")
		parsed, err := Parse(ctx, cache, f.pricesFor(t, cache, date), &entry.esi, entry.esi.KillmailHash, 0)
		if err != nil {
			t.Fatal(err)
		}
		total += parsed.Killmail.TotalValue

		// Resolve the day with the same types the parser asked about.
		ids := []int32{parsed.Killmail.VictimShipTypeID}
		for _, it := range parsed.Items {
			ids = append(ids, it.TypeID)
		}
		day, err := f.pricesFor(t, cache, date).On(ctx, date, ids)
		if err != nil {
			t.Fatal(err)
		}

		if id := parsed.Killmail.VictimShipTypeID; id != 0 {
			// Structures are anchored, not bought, so several genuinely have no
			// market price and are expected at the floor.
			if ty, ok := cache.Type(id); !ok || ty.CategoryID != categoryStructure {
				hulls++
				if day.Of(id) <= eve.FallbackPrice {
					hullsAtFloor++
					t.Logf("hull priced at the floor: killmail=%d kind=%s type=%d (%s)",
						entry.id, entry.kind, id, ty.Name)
				}
			}
		}
		for _, it := range parsed.Items {
			if it.Singleton == SingletonBPC {
				continue // priced by rule, not by market
			}
			items++
			if day.Of(it.TypeID) <= eve.FallbackPrice {
				itemsAtFloor++
			}
		}
	}

	if hulls == 0 || items == 0 {
		t.Fatal("the corpus resolved no prices at all")
	}

	// Ships trade constantly; a hull without a price means the snapshot for that
	// day is missing, not that nobody was selling.
	if hullsAtFloor*100 > hulls*2 {
		t.Errorf("%d of %d non-structure hulls priced at the floor — the price fixture is stale or wrong",
			hullsAtFloor, hulls)
	}
	// Some modules genuinely never trade; most do.
	if itemsAtFloor*100 > items*10 {
		t.Errorf("%d of %d items priced at the floor (%.1f%%) — expected under 10%%",
			itemsAtFloor, items, 100*float64(itemsAtFloor)/float64(items))
	}

	mean := total / float64(len(loadCorpus(t)))
	if mean < 1_000_000 {
		t.Errorf("mean killmail value is %.2f ISK — prices are not being applied", mean)
	}
	t.Logf("hulls priced %d/%d, items priced %d/%d, mean value %.0f ISK",
		hulls-hullsAtFloor, hulls, items-itemsAtFloor, items, mean)
}
