// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: 000_placeholder.sql

package dbgen

import (
	"context"
)

const sDEBuildNumber = `-- name: SDEBuildNumber :one
SELECT value FROM config WHERE key = $1
`

// placeholder so sqlc has something to parse
func (q *Queries) SDEBuildNumber(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRow(ctx, sDEBuildNumber, key)
	var value string
	err := row.Scan(&value)
	return value, err
}
