// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Alliance struct {
	AllianceID              int32              `json:"alliance_id"`
	Name                    string             `json:"name"`
	Ticker                  string             `json:"ticker"`
	CreatorID               *int32             `json:"creator_id"`
	CreatorCorporationID    *int32             `json:"creator_corporation_id"`
	ExecutorCorporationID   *int32             `json:"executor_corporation_id"`
	DateFounded             pgtype.Timestamptz `json:"date_founded"`
	FactionID               *int32             `json:"faction_id"`
	CorporationCount        *int32             `json:"corporation_count"`
	MemberCount             *int32             `json:"member_count"`
	Deleted                 *bool              `json:"deleted"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	CustomDescription       *string            `json:"custom_description"`
	CustomDescriptionFormat *string            `json:"custom_description_format"`
}

type Announcement struct {
	ID         int32              `json:"id"`
	Tier       int16              `json:"tier"`
	Title      string             `json:"title"`
	BodyMd     string             `json:"body_md"`
	BodyHtml   string             `json:"body_html"`
	Color      string             `json:"color"`
	Icon       *string            `json:"icon"`
	LinkUrl    *string            `json:"link_url"`
	LinkLabel  *string            `json:"link_label"`
	StartsAt   pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedBy  int64              `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

type AnnouncementDismissal struct {
	CharacterID    int64              `json:"character_id"`
	AnnouncementID int64              `json:"announcement_id"`
	DismissedAt    pgtype.Timestamptz `json:"dismissed_at"`
}

type Battle struct {
	BattleID             int32              `json:"battle_id"`
	SolarSystemID        int32              `json:"solar_system_id"`
	RegionID             *int32             `json:"region_id"`
	StartTime            pgtype.Timestamptz `json:"start_time"`
	EndTime              pgtype.Timestamptz `json:"end_time"`
	DurationMinutes      *int32             `json:"duration_minutes"`
	KillCount            *int32             `json:"kill_count"`
	TotalIskDestroyed    *float64           `json:"total_isk_destroyed"`
	IsMultiParty         *bool              `json:"is_multi_party"`
	IsCustom             *bool              `json:"is_custom"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	CreatedByCharacterID *int32             `json:"created_by_character_id"`
}

type BattleTeam struct {
	ID                int32    `json:"id"`
	BattleID          int32    `json:"battle_id"`
	TeamIndex         int16    `json:"team_index"`
	TotalKills        *int32   `json:"total_kills"`
	TotalLosses       *int32   `json:"total_losses"`
	TotalIskDestroyed *float64 `json:"total_isk_destroyed"`
	TotalIskLost      *float64 `json:"total_isk_lost"`
}

type BattleTeamMember struct {
	ID            int32    `json:"id"`
	BattleTeamID  int32    `json:"battle_team_id"`
	CorporationID int32    `json:"corporation_id"`
	AllianceID    *int32   `json:"alliance_id"`
	Kills         *int32   `json:"kills"`
	Losses        *int32   `json:"losses"`
	IskDestroyed  *float64 `json:"isk_destroyed"`
	IskLost       *float64 `json:"isk_lost"`
}

type BlogPost struct {
	ID                    int32              `json:"id"`
	Slug                  string             `json:"slug"`
	Title                 string             `json:"title"`
	Excerpt               *string            `json:"excerpt"`
	BodyMd                string             `json:"body_md"`
	BodyHtml              string             `json:"body_html"`
	CoverImageUrl         *string            `json:"cover_image_url"`
	Status                int16              `json:"status"`
	AuthorID              int64              `json:"author_id"`
	AuthorName            string             `json:"author_name"`
	PublishedAt           pgtype.Timestamptz `json:"published_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	Tags                  []string           `json:"tags"`
	AuthorCorporationID   *int32             `json:"author_corporation_id"`
	AuthorCorporationName *string            `json:"author_corporation_name"`
	AuthorAllianceID      *int32             `json:"author_alliance_id"`
	AuthorAllianceName    *string            `json:"author_alliance_name"`
}

type Bloodline struct {
	BloodlineID            int32   `json:"bloodline_id"`
	BloodlineName          *string `json:"bloodline_name"`
	RaceID                 *int32  `json:"race_id"`
	Description            *string `json:"description"`
	MaleDescription        *string `json:"male_description"`
	FemaleDescription      *string `json:"female_description"`
	ShortDescription       *string `json:"short_description"`
	ShortMaleDescription   *string `json:"short_male_description"`
	ShortFemaleDescription *string `json:"short_female_description"`
	ShipTypeID             *int32  `json:"ship_type_id"`
	CorporationID          *int32  `json:"corporation_id"`
	Perception             *int32  `json:"perception"`
	Willpower              *int32  `json:"willpower"`
	Charisma               *int32  `json:"charisma"`
	Memory                 *int32  `json:"memory"`
	Intelligence           *int32  `json:"intelligence"`
	IconID                 *int32  `json:"icon_id"`
}

type Blueprint struct {
	BlueprintTypeID    int32  `json:"blueprint_type_id"`
	MaxProductionLimit *int32 `json:"max_production_limit"`
}

type BlueprintActivity struct {
	BlueprintTypeID int32  `json:"blueprint_type_id"`
	Activity        string `json:"activity"`
	Time            int32  `json:"time"`
}

type BlueprintActivityMaterial struct {
	BlueprintTypeID int32  `json:"blueprint_type_id"`
	Activity        string `json:"activity"`
	MaterialTypeID  int32  `json:"material_type_id"`
	Quantity        int32  `json:"quantity"`
}

type BlueprintActivityProduct struct {
	BlueprintTypeID int32    `json:"blueprint_type_id"`
	Activity        string   `json:"activity"`
	ProductTypeID   int32    `json:"product_type_id"`
	Quantity        int32    `json:"quantity"`
	Probability     *float32 `json:"probability"`
}

type BlueprintActivitySkill struct {
	BlueprintTypeID int32  `json:"blueprint_type_id"`
	Activity        string `json:"activity"`
	SkillTypeID     int32  `json:"skill_type_id"`
	Level           int32  `json:"level"`
}

type Campaign struct {
	CampaignID               string             `json:"campaign_id"`
	Name                     string             `json:"name"`
	Description              *string            `json:"description"`
	CreatedByCharacterID     int32              `json:"created_by_character_id"`
	Status                   int16              `json:"status"`
	StartTime                pgtype.Timestamptz `json:"start_time"`
	EndTime                  pgtype.Timestamptz `json:"end_time"`
	Location                 []byte             `json:"location"`
	Stats                    []byte             `json:"stats"`
	ProcessedThrough         pgtype.Timestamptz `json:"processed_through"`
	LastActivityAt           pgtype.Timestamptz `json:"last_activity_at"`
	StatsUpdatedAt           pgtype.Timestamptz `json:"stats_updated_at"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	Visibility               int16              `json:"visibility"`
	AllowedEntities          []byte             `json:"allowed_entities"`
	ProcessingPaused         bool               `json:"processing_paused"`
	ProcessingNote           *string            `json:"processing_note"`
	EstimatedKillmails       *int32             `json:"estimated_killmails"`
	LastProcessingStartedAt  pgtype.Timestamptz `json:"last_processing_started_at"`
	LastProcessingDurationMs *int32             `json:"last_processing_duration_ms"`
	LastProcessingKillmails  *int32             `json:"last_processing_killmails"`
	LastProcessingError      *string            `json:"last_processing_error"`
}

type CampaignPrizePool struct {
	CampaignID        string             `json:"campaign_id"`
	Metric            int16              `json:"metric"`
	WinnerCount       int16              `json:"winner_count"`
	PayoutPercentages []int16            `json:"payout_percentages"`
	Status            int16              `json:"status"`
	FundedTotal       pgtype.Numeric     `json:"funded_total"`
	RulesLockedAt     pgtype.Timestamptz `json:"rules_locked_at"`
	FinalizedAt       pgtype.Timestamptz `json:"finalized_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type CampaignPrizeResult struct {
	CampaignID             string             `json:"campaign_id"`
	Rank                   int16              `json:"rank"`
	CharacterID            int32              `json:"character_id"`
	CharacterName          *string            `json:"character_name"`
	MetricValue            pgtype.Numeric     `json:"metric_value"`
	SecondaryValue         pgtype.Numeric     `json:"secondary_value"`
	PayoutPercentage       int16              `json:"payout_percentage"`
	PayoutAmount           pgtype.Numeric     `json:"payout_amount"`
	ClaimedAt              pgtype.Timestamptz `json:"claimed_at"`
	ClaimedByCharacterID   *int32             `json:"claimed_by_character_id"`
	PaidAt                 pgtype.Timestamptz `json:"paid_at"`
	PaidByAdminCharacterID *int32             `json:"paid_by_admin_character_id"`
	PaymentNote            *string            `json:"payment_note"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type CampaignScratchCandidate struct {
	CampaignID string `json:"campaign_id"`
	KillmailID int32  `json:"killmail_id"`
}

type CampaignScratchKillmail struct {
	CampaignID          string             `json:"campaign_id"`
	KillmailID          int32              `json:"killmail_id"`
	KillmailTime        pgtype.Timestamptz `json:"killmail_time"`
	Day                 pgtype.Date        `json:"day"`
	AdjValue            float64            `json:"adj_value"`
	VictimShipTypeID    *int32             `json:"victim_ship_type_id"`
	VictimShipGroupID   *int32             `json:"victim_ship_group_id"`
	VictimCharacterID   *int32             `json:"victim_character_id"`
	VictimCorporationID *int32             `json:"victim_corporation_id"`
	VictimAllianceID    *int32             `json:"victim_alliance_id"`
	SolarSystemID       *int32             `json:"solar_system_id"`
	RegionID            *int32             `json:"region_id"`
	VictimSide          *int16             `json:"victim_side"`
	AttackerMask        int32              `json:"attacker_mask"`
}

type CampaignSide struct {
	CampaignID   string  `json:"campaign_id"`
	SideIndex    int16   `json:"side_index"`
	Name         string  `json:"name"`
	Kills        int32   `json:"kills"`
	Losses       int32   `json:"losses"`
	IskDestroyed float64 `json:"isk_destroyed"`
	IskLost      float64 `json:"isk_lost"`
}

type CampaignSideEntity struct {
	ID           int32   `json:"id"`
	CampaignID   string  `json:"campaign_id"`
	SideIndex    int16   `json:"side_index"`
	EntityType   int16   `json:"entity_type"`
	EntityID     int32   `json:"entity_id"`
	Kills        int32   `json:"kills"`
	Losses       int32   `json:"losses"`
	IskDestroyed float64 `json:"isk_destroyed"`
	IskLost      float64 `json:"isk_lost"`
}

type CampaignStatsDaily struct {
	CampaignID   string      `json:"campaign_id"`
	SideIndex    int16       `json:"side_index"`
	Day          pgtype.Date `json:"day"`
	Kills        int32       `json:"kills"`
	Losses       int32       `json:"losses"`
	IskDestroyed float64     `json:"isk_destroyed"`
	IskLost      float64     `json:"isk_lost"`
}

type Celestial struct {
	ItemID          int32    `json:"item_id"`
	ItemName        *string  `json:"item_name"`
	TypeID          *int32   `json:"type_id"`
	GroupID         *int32   `json:"group_id"`
	SolarSystemID   *int32   `json:"solar_system_id"`
	ConstellationID *int32   `json:"constellation_id"`
	RegionID        *int32   `json:"region_id"`
	OrbitID         *int32   `json:"orbit_id"`
	X               *float64 `json:"x"`
	Y               *float64 `json:"y"`
	Z               *float64 `json:"z"`
	Radius          *float64 `json:"radius"`
	Security        *float64 `json:"security"`
	CelestialIndex  *int32   `json:"celestial_index"`
	OrbitIndex      *int32   `json:"orbit_index"`
}

type Character struct {
	CharacterID                           int32              `json:"character_id"`
	Name                                  string             `json:"name"`
	Description                           *string            `json:"description"`
	Birthday                              pgtype.Timestamptz `json:"birthday"`
	Gender                                *string            `json:"gender"`
	RaceID                                *int32             `json:"race_id"`
	BloodlineID                           *int32             `json:"bloodline_id"`
	SecurityStatus                        *float32           `json:"security_status"`
	Title                                 *string            `json:"title"`
	CorporationID                         *int32             `json:"corporation_id"`
	AllianceID                            *int32             `json:"alliance_id"`
	FactionID                             *int32             `json:"faction_id"`
	Deleted                               *bool              `json:"deleted"`
	LastActive                            pgtype.Timestamptz `json:"last_active"`
	CreatedAt                             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                             pgtype.Timestamptz `json:"updated_at"`
	CustomDescription                     *string            `json:"custom_description"`
	CustomDescriptionFormat               *string            `json:"custom_description_format"`
	AchievementPoints                     int32              `json:"achievement_points"`
	CorporationHistoryQueuedAt            pgtype.Timestamptz `json:"corporation_history_queued_at"`
	CorporationHistoryFetchedAt           pgtype.Timestamptz `json:"corporation_history_fetched_at"`
	CorporationHistorySyncedCorporationID *int32             `json:"corporation_history_synced_corporation_id"`
}

type CharacterCorporationHistory struct {
	CharacterID   int32              `json:"character_id"`
	RecordID      int32              `json:"record_id"`
	CorporationID int32              `json:"corporation_id"`
	StartDate     pgtype.Timestamptz `json:"start_date"`
}

type CharacterIntelDaily struct {
	CharacterID        int32       `json:"character_id"`
	ActivityDate       pgtype.Date `json:"activity_date"`
	Appearances        int32       `json:"appearances"`
	Solo               int32       `json:"solo"`
	SmallGang          int32       `json:"small_gang"`
	MidGang            int32       `json:"mid_gang"`
	Fleet              int32       `json:"fleet"`
	Blob               int32       `json:"blob"`
	SumAttackerCount   int64       `json:"sum_attacker_count"`
	MonitorAppearances int32       `json:"monitor_appearances"`
	ZeroDamageFleet    int32       `json:"zero_damage_fleet"`
	Highsec            int32       `json:"highsec"`
	Lowsec             int32       `json:"lowsec"`
	Nullsec            int32       `json:"nullsec"`
	GankAppearances    int32       `json:"gank_appearances"`
	AwoxKills          int32       `json:"awox_kills"`
	Losses             int32       `json:"losses"`
	CynoLosses         int32       `json:"cyno_losses"`
	CheapDeaths        int32       `json:"cheap_deaths"`
	BaitedDeaths       int32       `json:"baited_deaths"`
}

type CharacterIntelDirtyDay struct {
	ActivityDate pgtype.Date        `json:"activity_date"`
	DirtiedAt    pgtype.Timestamptz `json:"dirtied_at"`
}

type CharacterIntelRollupDay struct {
	ActivityDate pgtype.Date        `json:"activity_date"`
	RefreshedAt  pgtype.Timestamptz `json:"refreshed_at"`
}

type CharacterIntelShipDaily struct {
	CharacterID      int32              `json:"character_id"`
	ActivityDate     pgtype.Date        `json:"activity_date"`
	ShipTypeID       int32              `json:"ship_type_id"`
	Appearances      int32              `json:"appearances"`
	Losses           int32              `json:"losses"`
	LastAppearanceAt pgtype.Timestamptz `json:"last_appearance_at"`
	LastLossID       *int32             `json:"last_loss_id"`
	LastLossAt       pgtype.Timestamptz `json:"last_loss_at"`
}

type CharacterIntelTargetDaily struct {
	CharacterID  int32       `json:"character_id"`
	ActivityDate pgtype.Date `json:"activity_date"`
	AllianceID   int32       `json:"alliance_id"`
	Appearances  int32       `json:"appearances"`
}

type Coalition struct {
	CoalitionID          int64              `json:"coalition_id"`
	Slug                 string             `json:"slug"`
	Name                 string             `json:"name"`
	Description          string             `json:"description"`
	SourceUrl            *string            `json:"source_url"`
	Revision             int32              `json:"revision"`
	CreatedByCharacterID *int32             `json:"created_by_character_id"`
	UpdatedByCharacterID *int32             `json:"updated_by_character_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type CoalitionEdit struct {
	EditID              int64              `json:"edit_id"`
	CoalitionID         int64              `json:"coalition_id"`
	EditorCharacterID   *int32             `json:"editor_character_id"`
	EditorCharacterName string             `json:"editor_character_name"`
	Action              string             `json:"action"`
	Summary             string             `json:"summary"`
	Changes             []byte             `json:"changes"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type CoalitionMembership struct {
	CoalitionID        int64              `json:"coalition_id"`
	AllianceID         int32              `json:"alliance_id"`
	AddedByCharacterID *int32             `json:"added_by_character_id"`
	AddedAt            pgtype.Timestamptz `json:"added_at"`
}

type Comment struct {
	ID               int64              `json:"id"`
	TargetType       int16              `json:"target_type"`
	TargetID         int64              `json:"target_id"`
	TargetSlug       *string            `json:"target_slug"`
	DomainID         *int32             `json:"domain_id"`
	ParentID         *int64             `json:"parent_id"`
	RootID           *int64             `json:"root_id"`
	Depth            int16              `json:"depth"`
	BodyMd           string             `json:"body_md"`
	BodyHtml         string             `json:"body_html"`
	CharacterID      int64              `json:"character_id"`
	CharacterName    string             `json:"character_name"`
	CorporationID    int64              `json:"corporation_id"`
	CorporationName  string             `json:"corporation_name"`
	AllianceID       *int64             `json:"alliance_id"`
	AllianceName     *string            `json:"alliance_name"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	EditedAt         pgtype.Timestamptz `json:"edited_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy        *int64             `json:"deleted_by"`
	ReportsCount     int32              `json:"reports_count"`
	Flagged          bool               `json:"flagged"`
	ModerationStatus int16              `json:"moderation_status"`
	Visibility       int16              `json:"visibility"`
}

type CommentEdit struct {
	ID        int64              `json:"id"`
	CommentID int64              `json:"comment_id"`
	BodyMd    string             `json:"body_md"`
	EditedAt  pgtype.Timestamptz `json:"edited_at"`
	EditedBy  int64              `json:"edited_by"`
}

type CommentReport struct {
	ID           int64              `json:"id"`
	CommentID    int64              `json:"comment_id"`
	ReporterID   int64              `json:"reporter_id"`
	ReporterName string             `json:"reporter_name"`
	Reason       string             `json:"reason"`
	Message      *string            `json:"message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ResolvedAt   pgtype.Timestamptz `json:"resolved_at"`
	ResolvedBy   *int64             `json:"resolved_by"`
	Resolution   *string            `json:"resolution"`
}

type Config struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Constellation struct {
	ConstellationID   int32    `json:"constellation_id"`
	ConstellationName *string  `json:"constellation_name"`
	RegionID          *int32   `json:"region_id"`
	X                 *float64 `json:"x"`
	Y                 *float64 `json:"y"`
	Z                 *float64 `json:"z"`
	FactionID         *int32   `json:"faction_id"`
	Radius            *float64 `json:"radius"`
}

type Corporation struct {
	CorporationID                   int32              `json:"corporation_id"`
	Name                            string             `json:"name"`
	Ticker                          string             `json:"ticker"`
	Description                     *string            `json:"description"`
	DateFounded                     pgtype.Timestamptz `json:"date_founded"`
	Url                             *string            `json:"url"`
	CeoID                           *int32             `json:"ceo_id"`
	CreatorID                       *int32             `json:"creator_id"`
	HomeStationID                   *int32             `json:"home_station_id"`
	AllianceID                      *int32             `json:"alliance_id"`
	FactionID                       *int32             `json:"faction_id"`
	MemberCount                     *int32             `json:"member_count"`
	Shares                          *int64             `json:"shares"`
	TaxRate                         *float32           `json:"tax_rate"`
	WarEligible                     *bool              `json:"war_eligible"`
	Deleted                         *bool              `json:"deleted"`
	CreatedAt                       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                       pgtype.Timestamptz `json:"updated_at"`
	CustomDescription               *string            `json:"custom_description"`
	CustomDescriptionFormat         *string            `json:"custom_description_format"`
	LpTaxRate                       *float32           `json:"lp_tax_rate"`
	FriendlyFire                    *string            `json:"friendly_fire"`
	State                           *string            `json:"state"`
	Type                            *string            `json:"type"`
	Palette                         []byte             `json:"palette"`
	AllianceHistoryQueuedAt         pgtype.Timestamptz `json:"alliance_history_queued_at"`
	AllianceHistoryFetchedAt        pgtype.Timestamptz `json:"alliance_history_fetched_at"`
	AllianceHistorySyncedAllianceID *int32             `json:"alliance_history_synced_alliance_id"`
}

type CorporationAllianceHistory struct {
	CorporationID int32              `json:"corporation_id"`
	RecordID      int32              `json:"record_id"`
	AllianceID    *int32             `json:"alliance_id"`
	StartDate     pgtype.Timestamptz `json:"start_date"`
}

type CorporationWalletBalance struct {
	CorporationID int32              `json:"corporation_id"`
	Division      int32              `json:"division"`
	Balance       pgtype.Numeric     `json:"balance"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type CorporationWalletJournal struct {
	CorporationID int32              `json:"corporation_id"`
	Division      int32              `json:"division"`
	JournalID     int64              `json:"journal_id"`
	Date          pgtype.Timestamptz `json:"date"`
	RefType       string             `json:"ref_type"`
	Description   string             `json:"description"`
	Amount        pgtype.Numeric     `json:"amount"`
	Balance       pgtype.Numeric     `json:"balance"`
	FirstPartyID  *int64             `json:"first_party_id"`
	SecondPartyID *int64             `json:"second_party_id"`
	ContextID     *int64             `json:"context_id"`
	ContextIDType *string            `json:"context_id_type"`
	Reason        *string            `json:"reason"`
	Tax           pgtype.Numeric     `json:"tax"`
	TaxReceiverID *int64             `json:"tax_receiver_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type CorporationWalletToken struct {
	CorporationID                int32              `json:"corporation_id"`
	AuthorizedCharacterID        int32              `json:"authorized_character_id"`
	AuthorizedCharacterName      string             `json:"authorized_character_name"`
	AuthorizedCharacterOwnerHash string             `json:"authorized_character_owner_hash"`
	AuthorizedByAdminCharacterID int32              `json:"authorized_by_admin_character_id"`
	AccessToken                  string             `json:"access_token"`
	RefreshToken                 string             `json:"refresh_token"`
	TokenExpiry                  pgtype.Timestamptz `json:"token_expiry"`
	TokenType                    string             `json:"token_type"`
	Scopes                       []string           `json:"scopes"`
	Disabled                     bool               `json:"disabled"`
	LastBalanceSync              pgtype.Timestamptz `json:"last_balance_sync"`
	LastJournalSync              pgtype.Timestamptz `json:"last_journal_sync"`
	LastError                    *string            `json:"last_error"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                    pgtype.Timestamptz `json:"updated_at"`
}

type CustomDomain struct {
	ID              int32              `json:"id"`
	Subdomain       string             `json:"subdomain"`
	CustomHostname  *string            `json:"custom_hostname"`
	UserID          int32              `json:"user_id"`
	Entities        []byte             `json:"entities"`
	Theme           []byte             `json:"theme"`
	NavbarLinks     []byte             `json:"navbar_links"`
	SiteName        *string            `json:"site_name"`
	SiteDescription *string            `json:"site_description"`
	Active          bool               `json:"active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Widgets         []byte             `json:"widgets"`
	CampaignPolicy  int32              `json:"campaign_policy"`
}

type CustomDomainCampaign struct {
	DomainID           int32              `json:"domain_id"`
	CampaignID         string             `json:"campaign_id"`
	AddedByCharacterID int32              `json:"added_by_character_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	PublicOnDomain     bool               `json:"public_on_domain"`
}

type CustomPrice struct {
	TypeID int32       `json:"type_id"`
	Date   pgtype.Date `json:"date"`
	Price  float64     `json:"price"`
}

type DomainAsset struct {
	ID           int32              `json:"id"`
	DomainID     int32              `json:"domain_id"`
	Type         string             `json:"type"`
	Status       string             `json:"status"`
	StorageKey   string             `json:"storage_key"`
	ContentType  string             `json:"content_type"`
	FileSize     int32              `json:"file_size"`
	UploadedBy   int32              `json:"uploaded_by"`
	ReviewedBy   *int32             `json:"reviewed_by"`
	ReviewedAt   pgtype.Timestamptz `json:"reviewed_at"`
	RejectReason *string            `json:"reject_reason"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	FileHash     string             `json:"file_hash"`
}

type DrizzleMigration struct {
	ID        int32              `json:"id"`
	Hash      string             `json:"hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type EkWalletAccount struct {
	CharacterID     int32              `json:"character_id"`
	Balance         pgtype.Numeric     `json:"balance"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ReservedBalance pgtype.Numeric     `json:"reserved_balance"`
}

type EkWalletReservation struct {
	ID                    int64              `json:"id"`
	CharacterID           int32              `json:"character_id"`
	ExternalReference     string             `json:"external_reference"`
	TransactionType       int16              `json:"transaction_type"`
	Amount                pgtype.Numeric     `json:"amount"`
	Status                int16              `json:"status"`
	Description           string             `json:"description"`
	Metadata              []byte             `json:"metadata"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	CapturedAmount        pgtype.Numeric     `json:"captured_amount"`
	CapturedTransactionID *int64             `json:"captured_transaction_id"`
	CloseReason           *string            `json:"close_reason"`
	ClosedAt              pgtype.Timestamptz `json:"closed_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	CampaignID            *string            `json:"campaign_id"`
}

type EkWalletTransaction struct {
	ID                   int64              `json:"id"`
	CharacterID          int32              `json:"character_id"`
	Type                 int16              `json:"type"`
	Amount               pgtype.Numeric     `json:"amount"`
	BalanceAfter         pgtype.Numeric     `json:"balance_after"`
	Description          string             `json:"description"`
	ExternalReference    string             `json:"external_reference"`
	CorporationID        *int32             `json:"corporation_id"`
	Division             *int32             `json:"division"`
	JournalID            *int64             `json:"journal_id"`
	Metadata             []byte             `json:"metadata"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	RelatedTransactionID *int64             `json:"related_transaction_id"`
	CampaignID           *string            `json:"campaign_id"`
}

type EntityAchievement struct {
	EntityID        int32              `json:"entity_id"`
	AchievementID   string             `json:"achievement_id"`
	CurrentCount    *int32             `json:"current_count"`
	Threshold       int32              `json:"threshold"`
	CompletionTiers *int32             `json:"completion_tiers"`
	IsCompleted     *bool              `json:"is_completed"`
	Points          *int32             `json:"points"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	LastUpdated     pgtype.Timestamptz `json:"last_updated"`
	LevelThresholds []int32            `json:"level_thresholds"`
	PointUnit       int32              `json:"point_unit"`
}

type EntityRanking struct {
	EntityType        int16              `json:"entity_type"`
	EntityID          int32              `json:"entity_id"`
	RankingWindow     int16              `json:"ranking_window"`
	CombatPoints      int64              `json:"combat_points"`
	AchievementPoints int64              `json:"achievement_points"`
	EveKillRating     int32              `json:"eve_kill_rating"`
	CombatRank        int32              `json:"combat_rank"`
	AchievementRank   *int32             `json:"achievement_rank"`
	OverallRank       int32              `json:"overall_rank"`
	Population        int32              `json:"population"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type EntitySnapshot struct {
	EntityType             string      `json:"entity_type"`
	EntityID               int32       `json:"entity_id"`
	Date                   pgtype.Date `json:"date"`
	MemberCount            *int32      `json:"member_count"`
	AvgSecStatus           *float32    `json:"avg_sec_status"`
	PirateMembers          *int32      `json:"pirate_members"`
	CarebearMembers        *int32      `json:"carebear_members"`
	NeutralMembers         *int32      `json:"neutral_members"`
	TotalAchievementPoints *int32      `json:"total_achievement_points"`
	AvgAchievementPoints   *float32    `json:"avg_achievement_points"`
	TopAchieverID          *int32      `json:"top_achiever_id"`
	TopAchieverPoints      *int32      `json:"top_achiever_points"`
}

type EntityTracker struct {
	TrackerID            int64              `json:"tracker_id"`
	CharacterID          int32              `json:"character_id"`
	TargetType           string             `json:"target_type"`
	TargetID             int32              `json:"target_id"`
	TargetName           string             `json:"target_name"`
	TargetTicker         *string            `json:"target_ticker"`
	Enabled              bool               `json:"enabled"`
	NotificationsEnabled bool               `json:"notifications_enabled"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type EntityTrackerEvent struct {
	EventID    int64              `json:"event_id"`
	TrackerID  int64              `json:"tracker_id"`
	KillmailID int32              `json:"killmail_id"`
	MatchRole  string             `json:"match_role"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type EntityTrackerNotification struct {
	NotificationID int64              `json:"notification_id"`
	EventID        int64              `json:"event_id"`
	CharacterID    int32              `json:"character_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ReadAt         pgtype.Timestamptz `json:"read_at"`
}

type EsiKillmailDelayed struct {
	KillmailID   int32              `json:"killmail_id"`
	KillmailHash string             `json:"killmail_hash"`
	DelayedUntil pgtype.Timestamptz `json:"delayed_until"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type EsiRequestLog struct {
	ID                  int64              `json:"id"`
	CharacterID         int32              `json:"character_id"`
	Endpoint            string             `json:"endpoint"`
	Method              string             `json:"method"`
	StatusCode          *int16             `json:"status_code"`
	Success             bool               `json:"success"`
	ErrorMessage        *string            `json:"error_message"`
	ItemsReturned       *int32             `json:"items_returned"`
	NewItems            *int32             `json:"new_items"`
	Source              string             `json:"source"`
	RequestDurationMs   *int32             `json:"request_duration_ms"`
	EsiErrorLimitRemain *int16             `json:"esi_error_limit_remain"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	NewItemIds          []byte             `json:"new_item_ids"`
}

type EvekillSchemaMigration struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Checksum    string             `json:"checksum"`
	Kind        string             `json:"kind"`
	AppliedAt   pgtype.Timestamptz `json:"applied_at"`
	ExecutionMs *int32             `json:"execution_ms"`
	Metadata    []byte             `json:"metadata"`
}

type Faction struct {
	FactionID            int32    `json:"faction_id"`
	Name                 *string  `json:"name"`
	Description          *string  `json:"description"`
	CorporationID        *int32   `json:"corporation_id"`
	MilitiaCorporationID *int32   `json:"militia_corporation_id"`
	SolarSystemID        *int32   `json:"solar_system_id"`
	IconID               *int32   `json:"icon_id"`
	SizeFactor           *float64 `json:"size_factor"`
	StationCount         *int32   `json:"station_count"`
	StationSystemCount   *int32   `json:"station_system_count"`
	RaceIds              []int32  `json:"race_ids"`
}

type FeedQueue struct {
	Seq        int64              `json:"seq"`
	KillmailID int32              `json:"killmail_id"`
	InsertedAt pgtype.Timestamptz `json:"inserted_at"`
}

type Fitting struct {
	FitHash     string             `json:"fit_hash"`
	ShipTypeID  int32              `json:"ship_type_id"`
	FamilyHash  string             `json:"family_hash"`
	FirstSeenAt pgtype.Timestamptz `json:"first_seen_at"`
}

type FittingItem struct {
	FitHash      string `json:"fit_hash"`
	SlotGroup    int16  `json:"slot_group"`
	Ordinal      int16  `json:"ordinal"`
	TypeID       int32  `json:"type_id"`
	ChargeTypeID *int32 `json:"charge_type_id"`
	Quantity     int16  `json:"quantity"`
}

type FittingStat struct {
	FitHash                string             `json:"fit_hash"`
	ShipTypeID             int32              `json:"ship_type_id"`
	SkillLevel             int16              `json:"skill_level"`
	DpsWithReload          *float64           `json:"dps_with_reload"`
	DpsWithoutReload       *float64           `json:"dps_without_reload"`
	Alpha                  *float64           `json:"alpha"`
	Ehp                    *float64           `json:"ehp"`
	ShieldEhp              *float64           `json:"shield_ehp"`
	ArmorEhp               *float64           `json:"armor_ehp"`
	HullEhp                *float64           `json:"hull_ehp"`
	ShieldBoost            *float64           `json:"shield_boost"`
	ShieldEffectiveBoost   *float64           `json:"shield_effective_boost"`
	ArmorRepair            *float64           `json:"armor_repair"`
	ArmorEffectiveRepair   *float64           `json:"armor_effective_repair"`
	HullRepair             *float64           `json:"hull_repair"`
	HullEffectiveRepair    *float64           `json:"hull_effective_repair"`
	PassiveShield          *float64           `json:"passive_shield"`
	PassiveShieldEffective *float64           `json:"passive_shield_effective"`
	RemoteShield           *float64           `json:"remote_shield"`
	RemoteArmor            *float64           `json:"remote_armor"`
	RemoteHull             *float64           `json:"remote_hull"`
	RemoteCap              *float64           `json:"remote_cap"`
	Neut                   *float64           `json:"neut"`
	Nos                    *float64           `json:"nos"`
	CapStable              bool               `json:"cap_stable"`
	CapDepletesIn          *float64           `json:"cap_depletes_in"`
	CapCapacity            *float64           `json:"cap_capacity"`
	CapPeakDelta           *float64           `json:"cap_peak_delta"`
	MaxVelocity            *float64           `json:"max_velocity"`
	AlignTime              *float64           `json:"align_time"`
	SignatureRadius        *float64           `json:"signature_radius"`
	MaxTargetRange         *float64           `json:"max_target_range"`
	ScanResolution         *float64           `json:"scan_resolution"`
	EngineVersion          string             `json:"engine_version"`
	SdeVersion             string             `json:"sde_version"`
	CalculatedAt           pgtype.Timestamptz `json:"calculated_at"`
	ShieldHp               *float64           `json:"shield_hp"`
	ArmorHp                *float64           `json:"armor_hp"`
	HullHp                 *float64           `json:"hull_hp"`
	ShieldEmResist         *float64           `json:"shield_em_resist"`
	ShieldThermalResist    *float64           `json:"shield_thermal_resist"`
	ShieldKineticResist    *float64           `json:"shield_kinetic_resist"`
	ShieldExplosiveResist  *float64           `json:"shield_explosive_resist"`
	ArmorEmResist          *float64           `json:"armor_em_resist"`
	ArmorThermalResist     *float64           `json:"armor_thermal_resist"`
	ArmorKineticResist     *float64           `json:"armor_kinetic_resist"`
	ArmorExplosiveResist   *float64           `json:"armor_explosive_resist"`
	HullEmResist           *float64           `json:"hull_em_resist"`
	HullThermalResist      *float64           `json:"hull_thermal_resist"`
	HullKineticResist      *float64           `json:"hull_kinetic_resist"`
	HullExplosiveResist    *float64           `json:"hull_explosive_resist"`
}

type FittingStatDistributionBucket struct {
	ShipTypeID       int32   `json:"ship_type_id"`
	WindowDays       int16   `json:"window_days"`
	Metric           string  `json:"metric"`
	Bucket           int16   `json:"bucket"`
	LowerBound       float64 `json:"lower_bound"`
	UpperBound       float64 `json:"upper_bound"`
	FitCount         int32   `json:"fit_count"`
	ObservationCount int64   `json:"observation_count"`
}

type FittingStatDistributionSummary struct {
	ShipTypeID       int32              `json:"ship_type_id"`
	WindowDays       int16              `json:"window_days"`
	Metric           string             `json:"metric"`
	FitCount         int32              `json:"fit_count"`
	ObservationCount int64              `json:"observation_count"`
	Minimum          float64            `json:"minimum"`
	Maximum          float64            `json:"maximum"`
	P10              float64            `json:"p10"`
	P25              float64            `json:"p25"`
	Median           float64            `json:"median"`
	P75              float64            `json:"p75"`
	P90              float64            `json:"p90"`
	LowerBound       float64            `json:"lower_bound"`
	UpperBound       float64            `json:"upper_bound"`
	CalculatedAt     pgtype.Timestamptz `json:"calculated_at"`
}

type FwFactionStat struct {
	FactionID         int32              `json:"faction_id"`
	Pilots            int32              `json:"pilots"`
	SystemsControlled int32              `json:"systems_controlled"`
	KillsYesterday    int32              `json:"kills_yesterday"`
	KillsLastWeek     int32              `json:"kills_last_week"`
	KillsTotal        int32              `json:"kills_total"`
	VpYesterday       int32              `json:"vp_yesterday"`
	VpLastWeek        int32              `json:"vp_last_week"`
	VpTotal           int64              `json:"vp_total"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type FwLeaderboard struct {
	EntityType string             `json:"entity_type"`
	EntityID   int32              `json:"entity_id"`
	Metric     string             `json:"metric"`
	Period     string             `json:"period"`
	Amount     int64              `json:"amount"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type FwSystem struct {
	SolarSystemID          int32              `json:"solar_system_id"`
	OwnerFactionID         int32              `json:"owner_faction_id"`
	OccupierFactionID      int32              `json:"occupier_faction_id"`
	Contested              string             `json:"contested"`
	VictoryPoints          int32              `json:"victory_points"`
	VictoryPointsThreshold int32              `json:"victory_points_threshold"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type FwSystemHistory struct {
	ID                   int32              `json:"id"`
	SolarSystemID        int32              `json:"solar_system_id"`
	OldOccupierFactionID int32              `json:"old_occupier_faction_id"`
	NewOccupierFactionID int32              `json:"new_occupier_faction_id"`
	FlippedAt            pgtype.Timestamptz `json:"flipped_at"`
}

type InsurancePrice struct {
	TypeID    int32   `json:"type_id"`
	LevelName string  `json:"level_name"`
	Cost      float64 `json:"cost"`
	Payout    float64 `json:"payout"`
}

type InvCategory struct {
	CategoryID int32   `json:"category_id"`
	Name       *string `json:"name"`
	Published  *bool   `json:"published"`
	IconID     *int32  `json:"icon_id"`
}

type InvFlag struct {
	FlagID   int32   `json:"flag_id"`
	FlagName *string `json:"flag_name"`
	FlagText *string `json:"flag_text"`
	OrderID  *int32  `json:"order_id"`
}

type InvGroup struct {
	GroupID    int32   `json:"group_id"`
	CategoryID *int32  `json:"category_id"`
	Name       *string `json:"name"`
	Published  *bool   `json:"published"`
	IconID     *int32  `json:"icon_id"`
}

type InvMarketGroup struct {
	MarketGroupID int32   `json:"market_group_id"`
	ParentGroupID *int32  `json:"parent_group_id"`
	Name          *string `json:"name"`
	Description   *string `json:"description"`
	IconID        *int32  `json:"icon_id"`
	HasTypes      *bool   `json:"has_types"`
}

type InvMetaGroup struct {
	MetaGroupID int32   `json:"meta_group_id"`
	Name        *string `json:"name"`
	IconID      *int32  `json:"icon_id"`
	IconSuffix  *string `json:"icon_suffix"`
}

type InvType struct {
	TypeID                int32    `json:"type_id"`
	GroupID               *int32   `json:"group_id"`
	CategoryID            *int32   `json:"category_id"`
	Name                  *string  `json:"name"`
	Description           *string  `json:"description"`
	Mass                  *float64 `json:"mass"`
	Volume                *float64 `json:"volume"`
	Capacity              *float64 `json:"capacity"`
	PortionSize           *int32   `json:"portion_size"`
	PackagedVolume        *float64 `json:"packaged_volume"`
	Radius                *float64 `json:"radius"`
	Published             *bool    `json:"published"`
	MarketGroupID         *int32   `json:"market_group_id"`
	IconID                *int32   `json:"icon_id"`
	SoundID               *int32   `json:"sound_id"`
	GraphicID             *int32   `json:"graphic_id"`
	MetaGroupID           *int32   `json:"meta_group_id"`
	RaceID                *int32   `json:"race_id"`
	FactionID             *int32   `json:"faction_id"`
	BasePrice             *float64 `json:"base_price"`
	VariationParentTypeID *int32   `json:"variation_parent_type_id"`
}

type Killmail struct {
	KillmailID          int32              `json:"killmail_id"`
	KillmailTime        pgtype.Timestamptz `json:"killmail_time"`
	KillmailHash        string             `json:"killmail_hash"`
	SolarSystemID       int32              `json:"solar_system_id"`
	ConstellationID     *int32             `json:"constellation_id"`
	RegionID            *int32             `json:"region_id"`
	PositionX           *float64           `json:"position_x"`
	PositionY           *float64           `json:"position_y"`
	PositionZ           *float64           `json:"position_z"`
	VictimCharacterID   *int32             `json:"victim_character_id"`
	VictimCorporationID *int32             `json:"victim_corporation_id"`
	VictimAllianceID    *int32             `json:"victim_alliance_id"`
	VictimFactionID     *int32             `json:"victim_faction_id"`
	VictimShipTypeID    *int32             `json:"victim_ship_type_id"`
	VictimShipGroupID   *int32             `json:"victim_ship_group_id"`
	VictimDamageTaken   *int32             `json:"victim_damage_taken"`
	TotalValue          *float64           `json:"total_value"`
	FittedValue         *float64           `json:"fitted_value"`
	DroppedValue        *float64           `json:"dropped_value"`
	DestroyedValue      *float64           `json:"destroyed_value"`
	Points              *int32             `json:"points"`
	AttackerCount       *int32             `json:"attacker_count"`
	IsNpc               *bool              `json:"is_npc"`
	IsSolo              *bool              `json:"is_solo"`
	WarID               *int32             `json:"war_id"`
	Blob                *bool              `json:"blob"`
	IsAwox              bool               `json:"is_awox"`
	IsCapitalInvolved   bool               `json:"is_capital_involved"`
	IsSuperInvolved     bool               `json:"is_super_involved"`
	IsTitanInvolved     bool               `json:"is_titan_involved"`
	IsAtShipInvolved    bool               `json:"is_at_ship_involved"`
	FwWinnerFactionID   *int32             `json:"fw_winner_faction_id"`
}

type KillmailAttacker struct {
	KillmailID     int32              `json:"killmail_id"`
	AttackerIndex  int32              `json:"attacker_index"`
	CharacterID    *int32             `json:"character_id"`
	CorporationID  *int32             `json:"corporation_id"`
	AllianceID     *int32             `json:"alliance_id"`
	FactionID      *int32             `json:"faction_id"`
	ShipTypeID     *int32             `json:"ship_type_id"`
	ShipGroupID    *int32             `json:"ship_group_id"`
	WeaponTypeID   *int32             `json:"weapon_type_id"`
	DamageDone     *int32             `json:"damage_done"`
	FinalBlow      *bool              `json:"final_blow"`
	SecurityStatus *float32           `json:"security_status"`
	KillmailTime   pgtype.Timestamptz `json:"killmail_time"`
	// Conserved share of killmails.points allocated to this player attacker; NPC and duplicate character rows receive zero
	Points int64 `json:"points"`
}

type KillmailFitting struct {
	KillmailID          int32              `json:"killmail_id"`
	FitHash             string             `json:"fit_hash"`
	ShipTypeID          int32              `json:"ship_type_id"`
	KillTime            pgtype.Timestamptz `json:"kill_time"`
	VictimAllianceID    *int32             `json:"victim_alliance_id"`
	VictimCorporationID *int32             `json:"victim_corporation_id"`
}

type KillmailItem struct {
	KillmailID        int32  `json:"killmail_id"`
	ItemIndex         int32  `json:"item_index"`
	TypeID            int32  `json:"type_id"`
	FlagID            int32  `json:"flag_id"`
	QuantityDropped   *int64 `json:"quantity_dropped"`
	QuantityDestroyed *int64 `json:"quantity_destroyed"`
	Singleton         *int16 `json:"singleton"`
	ParentIndex       *int32 `json:"parent_index"`
}

type KillmailProcessing struct {
	KillmailID       int32              `json:"killmail_id"`
	EffectsCompleted int32              `json:"effects_completed"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type KillsDailyCount struct {
	Date  pgtype.Date `json:"date"`
	Type  string      `json:"type"`
	Count int64       `json:"count"`
}

type MarketOrder struct {
	OrderID          int64              `json:"order_id"`
	Duration         int16              `json:"duration"`
	IsBuyOrder       bool               `json:"is_buy_order"`
	Issued           pgtype.Timestamptz `json:"issued"`
	LocationID       int64              `json:"location_id"`
	MinVolume        int64              `json:"min_volume"`
	Price            float64            `json:"price"`
	OrderRange       string             `json:"order_range"`
	SystemID         int32              `json:"system_id"`
	TypeID           int32              `json:"type_id"`
	VolumeRemain     int64              `json:"volume_remain"`
	VolumeTotal      int64              `json:"volume_total"`
	HttpLastModified pgtype.Timestamptz `json:"http_last_modified"`
	StationID        *int64             `json:"station_id"`
	RegionID         int32              `json:"region_id"`
	ConstellationID  *int32             `json:"constellation_id"`
	SnapshotAt       pgtype.Timestamptz `json:"snapshot_at"`
}

type MarketRegionHistory struct {
	TypeID           int32              `json:"type_id"`
	RegionID         int32              `json:"region_id"`
	Date             pgtype.Date        `json:"date"`
	Average          *float64           `json:"average"`
	Highest          *float64           `json:"highest"`
	Lowest           *float64           `json:"lowest"`
	OrderCount       *int32             `json:"order_count"`
	Volume           *int64             `json:"volume"`
	HttpLastModified pgtype.Timestamptz `json:"http_last_modified"`
}

type MarketSourceFile struct {
	SourcePath         string             `json:"source_path"`
	Dataset            string             `json:"dataset"`
	Etag               *string            `json:"etag"`
	SizeBytes          int64              `json:"size_bytes"`
	SourceLastModified pgtype.Timestamptz `json:"source_last_modified"`
	FileTime           pgtype.Timestamptz `json:"file_time"`
	RowsImported       int64              `json:"rows_imported"`
	ImportedAt         pgtype.Timestamptz `json:"imported_at"`
}

type ModerationQueue struct {
	ID              int64              `json:"id"`
	TargetKind      int16              `json:"target_kind"`
	TargetID        int64              `json:"target_id"`
	Body            string             `json:"body"`
	BodyFormat      *string            `json:"body_format"`
	RenderedHtml    *string            `json:"rendered_html"`
	CharacterID     int64              `json:"character_id"`
	CharacterName   string             `json:"character_name"`
	CorporationID   *int64             `json:"corporation_id"`
	CorporationName *string            `json:"corporation_name"`
	AllianceID      *int64             `json:"alliance_id"`
	AllianceName    *string            `json:"alliance_name"`
	AiAction        *string            `json:"ai_action"`
	AiCategory      *string            `json:"ai_category"`
	AiMaxScore      *float32           `json:"ai_max_score"`
	AiScores        []byte             `json:"ai_scores"`
	AiSource        *string            `json:"ai_source"`
	Status          int16              `json:"status"`
	SubmittedAt     pgtype.Timestamptz `json:"submitted_at"`
	ReviewedAt      pgtype.Timestamptz `json:"reviewed_at"`
	ReviewedBy      *int64             `json:"reviewed_by"`
	ReviewNotes     *string            `json:"review_notes"`
}

type NpcCorporation struct {
	CorporationID int32    `json:"corporation_id"`
	Name          *string  `json:"name"`
	Description   *string  `json:"description"`
	TickerName    *string  `json:"ticker_name"`
	CeoID         *int32   `json:"ceo_id"`
	StationID     *int32   `json:"station_id"`
	Size          *string  `json:"size"`
	Extent        *string  `json:"extent"`
	TaxRate       *float64 `json:"tax_rate"`
	Deleted       *bool    `json:"deleted"`
}

type OldKillmail struct {
	KillmailID          int32            `json:"killmail_id"`
	KillmailTime        pgtype.Timestamp `json:"killmail_time"`
	RawText             string           `json:"raw_text"`
	VictimName          *string          `json:"victim_name"`
	VictimCorp          *string          `json:"victim_corp"`
	VictimAlliance      *string          `json:"victim_alliance"`
	VictimShip          *string          `json:"victim_ship"`
	SystemName          *string          `json:"system_name"`
	Security            *float32         `json:"security"`
	TotalValue          *float32         `json:"total_value"`
	FinalBlowName       *string          `json:"final_blow_name"`
	VictimCharacterID   *int32           `json:"victim_character_id"`
	VictimCorporationID *int32           `json:"victim_corporation_id"`
	VictimAllianceID    *int32           `json:"victim_alliance_id"`
	VictimShipTypeID    *int32           `json:"victim_ship_type_id"`
	SolarSystemID       *int32           `json:"solar_system_id"`
}

type OldKillmailAttacker struct {
	ID             int32    `json:"id"`
	KillmailID     int32    `json:"killmail_id"`
	Name           *string  `json:"name"`
	Corp           *string  `json:"corp"`
	Alliance       *string  `json:"alliance"`
	Ship           *string  `json:"ship"`
	Weapon         *string  `json:"weapon"`
	SecurityStatus *float32 `json:"security_status"`
	FinalBlow      *bool    `json:"final_blow"`
	CharacterID    *int32   `json:"character_id"`
	CorporationID  *int32   `json:"corporation_id"`
	AllianceID     *int32   `json:"alliance_id"`
	ShipTypeID     *int32   `json:"ship_type_id"`
	WeaponTypeID   *int32   `json:"weapon_type_id"`
}

type OldKillmailItem struct {
	ID         int32   `json:"id"`
	KillmailID int32   `json:"killmail_id"`
	Name       string  `json:"name"`
	Quantity   *int32  `json:"quantity"`
	Location   *string `json:"location"`
	TypeID     *int32  `json:"type_id"`
}

type Price struct {
	TypeID     int32       `json:"type_id"`
	RegionID   int32       `json:"region_id"`
	Date       pgtype.Date `json:"date"`
	Average    *float64    `json:"average"`
	Highest    *float64    `json:"highest"`
	Lowest     *float64    `json:"lowest"`
	OrderCount *int32      `json:"order_count"`
	Volume     *int64      `json:"volume"`
}

type Race struct {
	RaceID           int32   `json:"race_id"`
	RaceName         *string `json:"race_name"`
	Description      *string `json:"description"`
	ShortDescription *string `json:"short_description"`
	IconID           *int32  `json:"icon_id"`
}

type Region struct {
	RegionID        int32    `json:"region_id"`
	Name            *string  `json:"name"`
	Description     *string  `json:"description"`
	CenterX         *float64 `json:"center_x"`
	CenterY         *float64 `json:"center_y"`
	CenterZ         *float64 `json:"center_z"`
	FactionID       *int32   `json:"faction_id"`
	WormholeClassID *int32   `json:"wormhole_class_id"`
	NebulaID        *int32   `json:"nebula_id"`
}

type Scan struct {
	Hash        string             `json:"hash"`
	ScanType    string             `json:"scan_type"`
	Input       string             `json:"input"`
	Result      []byte             `json:"result"`
	CharacterID int32              `json:"character_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type SolarSystem struct {
	SolarSystemID   int32    `json:"solar_system_id"`
	SystemName      *string  `json:"system_name"`
	ConstellationID *int32   `json:"constellation_id"`
	RegionID        *int32   `json:"region_id"`
	X               *float64 `json:"x"`
	Y               *float64 `json:"y"`
	Z               *float64 `json:"z"`
	Security        *float64 `json:"security"`
	SecurityClass   *string  `json:"security_class"`
	FactionID       *int32   `json:"faction_id"`
	Border          *bool    `json:"border"`
	Fringe          *bool    `json:"fringe"`
	Corridor        *bool    `json:"corridor"`
	Hub             *bool    `json:"hub"`
	International   *bool    `json:"international"`
	Regional        *bool    `json:"regional"`
	Luminosity      *float64 `json:"luminosity"`
	Radius          *float64 `json:"radius"`
	SunTypeID       *int32   `json:"sun_type_id"`
	X2d             *float64 `json:"x2d"`
	Z2d             *float64 `json:"z2d"`
}

type SolarSystemJump struct {
	FromSolarSystemID   int32  `json:"from_solar_system_id"`
	ToSolarSystemID     int32  `json:"to_solar_system_id"`
	FromConstellationID *int32 `json:"from_constellation_id"`
	ToConstellationID   *int32 `json:"to_constellation_id"`
	FromRegionID        *int32 `json:"from_region_id"`
	ToRegionID          *int32 `json:"to_region_id"`
}

type Sovereignty struct {
	SystemID      int32              `json:"system_id"`
	AllianceID    *int32             `json:"alliance_id"`
	CorporationID *int32             `json:"corporation_id"`
	FactionID     *int32             `json:"faction_id"`
	DateAdded     pgtype.Timestamptz `json:"date_added"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type SovereigntyHistory struct {
	ID            int32              `json:"id"`
	SystemID      int32              `json:"system_id"`
	AllianceID    *int32             `json:"alliance_id"`
	CorporationID *int32             `json:"corporation_id"`
	FactionID     *int32             `json:"faction_id"`
	DateAdded     pgtype.Timestamptz `json:"date_added"`
}

type Stat struct {
	EntityType       int16       `json:"entity_type"`
	EntityID         int32       `json:"entity_id"`
	PeriodType       int16       `json:"period_type"`
	PeriodStart      pgtype.Date `json:"period_start"`
	Kills            *int32      `json:"kills"`
	Losses           *int32      `json:"losses"`
	SoloKills        *int32      `json:"solo_kills"`
	SoloLosses       *int32      `json:"solo_losses"`
	NpcLosses        *int32      `json:"npc_losses"`
	FinalBlows       *int32      `json:"final_blows"`
	Points           *int32      `json:"points"`
	IskDestroyed     *float64    `json:"isk_destroyed"`
	IskLost          *float64    `json:"isk_lost"`
	DamageDealt      *int64      `json:"damage_dealt"`
	DamageTaken      *int64      `json:"damage_taken"`
	SumAttackerCount *int64      `json:"sum_attacker_count"`
}

type Station struct {
	StationID                int32    `json:"station_id"`
	StationName              *string  `json:"station_name"`
	TypeID                   *int32   `json:"type_id"`
	CorporationID            *int32   `json:"corporation_id"`
	SolarSystemID            *int32   `json:"solar_system_id"`
	ConstellationID          *int32   `json:"constellation_id"`
	RegionID                 *int32   `json:"region_id"`
	OperationID              *int32   `json:"operation_id"`
	OrbitID                  *int32   `json:"orbit_id"`
	OrbitIndex               *int32   `json:"orbit_index"`
	CelestialIndex           *int32   `json:"celestial_index"`
	X                        *float64 `json:"x"`
	Y                        *float64 `json:"y"`
	Z                        *float64 `json:"z"`
	Security                 *float64 `json:"security"`
	ReprocessingEfficiency   *float64 `json:"reprocessing_efficiency"`
	ReprocessingStationsTake *float64 `json:"reprocessing_stations_take"`
}

type StationOperation struct {
	OperationID   int32   `json:"operation_id"`
	OperationName *string `json:"operation_name"`
	Description   *string `json:"description"`
	ActivityID    *int32  `json:"activity_id"`
	Services      []int32 `json:"services"`
}

type StatsBreakdown struct {
	EntityType       int16              `json:"entity_type"`
	EntityID         int32              `json:"entity_id"`
	PeriodType       int16              `json:"period_type"`
	PeriodStart      pgtype.Date        `json:"period_start"`
	DimCategory      int16              `json:"dim_category"`
	DimID            int32              `json:"dim_id"`
	Kills            *int32             `json:"kills"`
	Losses           *int32             `json:"losses"`
	IskDestroyed     *float64           `json:"isk_destroyed"`
	IskLost          *float64           `json:"isk_lost"`
	LastKillmailID   *int32             `json:"last_killmail_id"`
	LastKillmailTime pgtype.Timestamptz `json:"last_killmail_time"`
}

type StatsLeaderboard struct {
	EntityType  int16       `json:"entity_type"`
	PeriodType  int16       `json:"period_type"`
	PeriodStart pgtype.Date `json:"period_start"`
	Metric      int16       `json:"metric"`
	Rank        int16       `json:"rank"`
	EntityID    int32       `json:"entity_id"`
	Value       *float64    `json:"value"`
}

type Structure struct {
	StructureID     int64              `json:"structure_id"`
	Name            *string            `json:"name"`
	OwnerID         *int32             `json:"owner_id"`
	SolarSystemID   *int32             `json:"solar_system_id"`
	ConstellationID *int32             `json:"constellation_id"`
	RegionID        *int32             `json:"region_id"`
	TypeID          *int32             `json:"type_id"`
	X               *float64           `json:"x"`
	Y               *float64           `json:"y"`
	Z               *float64           `json:"z"`
	IsPublic        *bool              `json:"is_public"`
	IsMarket        *bool              `json:"is_market"`
	FirstSeen       pgtype.Timestamptz `json:"first_seen"`
	LastSeen        pgtype.Timestamptz `json:"last_seen"`
}

type SystemActivity struct {
	SystemID  int32              `json:"system_id"`
	Timestamp pgtype.Timestamptz `json:"timestamp"`
	ShipKills *int32             `json:"ship_kills"`
	NpcKills  *int32             `json:"npc_kills"`
	PodKills  *int32             `json:"pod_kills"`
	ShipJumps *int32             `json:"ship_jumps"`
}

type TypeDogmaAttribute struct {
	TypeID      int32   `json:"type_id"`
	AttributeID int32   `json:"attribute_id"`
	Value       float64 `json:"value"`
}

type TypeDogmaEffect struct {
	TypeID    int32 `json:"type_id"`
	EffectID  int32 `json:"effect_id"`
	IsDefault *bool `json:"is_default"`
}

type TypeMaterial struct {
	TypeID         int32 `json:"type_id"`
	MaterialTypeID int32 `json:"material_type_id"`
	Quantity       int32 `json:"quantity"`
}

type User struct {
	CharacterID            int32              `json:"character_id"`
	CharacterName          string             `json:"character_name"`
	CharacterOwnerHash     string             `json:"character_owner_hash"`
	SessionID              pgtype.UUID        `json:"session_id"`
	IsAdmin                bool               `json:"is_admin"`
	LastLogin              pgtype.Timestamptz `json:"last_login"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	LastSeenNotificationID int64              `json:"last_seen_notification_id"`
	DiscordUserID          *string            `json:"discord_user_id"`
}

type UserConfig struct {
	CharacterID int32              `json:"character_id"`
	Key         string             `json:"key"`
	Value       []byte             `json:"value"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type UserEsiToken struct {
	ID                    int32              `json:"id"`
	CharacterID           int32              `json:"character_id"`
	AccessToken           string             `json:"access_token"`
	RefreshToken          string             `json:"refresh_token"`
	TokenExpiry           pgtype.Timestamptz `json:"token_expiry"`
	TokenType             string             `json:"token_type"`
	Scopes                []string           `json:"scopes"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	LastFetched           pgtype.Timestamptz `json:"last_fetched"`
	Disabled              bool               `json:"disabled"`
	Delay                 int32              `json:"delay"`
	RevokedScopes         []string           `json:"revoked_scopes"`
	CharacterFailureCount int32              `json:"character_failure_count"`
	ScopesRevokedAt       pgtype.Timestamptz `json:"scopes_revoked_at"`
}

type UserFitting struct {
	FitID            string             `json:"fit_id"`
	OwnerCharacterID int32              `json:"owner_character_id"`
	ShipTypeID       int32              `json:"ship_type_id"`
	Name             string             `json:"name"`
	Description      *string            `json:"description"`
	Visibility       int16              `json:"visibility"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	RatingAvg        *float32           `json:"rating_avg"`
	RatingCount      int32              `json:"rating_count"`
}

type UserFittingItem struct {
	FitID        string `json:"fit_id"`
	SlotGroup    int16  `json:"slot_group"`
	Ordinal      int16  `json:"ordinal"`
	TypeID       int32  `json:"type_id"`
	State        int16  `json:"state"`
	ChargeTypeID *int32 `json:"charge_type_id"`
	Quantity     int16  `json:"quantity"`
}

type UserFittingRating struct {
	FitID            string             `json:"fit_id"`
	RaterCharacterID int32              `json:"rater_character_id"`
	Rating           int16              `json:"rating"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type UserSession struct {
	ID          int32              `json:"id"`
	SessionID   pgtype.UUID        `json:"session_id"`
	CharacterID int32              `json:"character_id"`
	IpAddress   *string            `json:"ip_address"`
	CountryCode *string            `json:"country_code"`
	UserAgent   *string            `json:"user_agent"`
	ClientHint  *string            `json:"client_hint"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

type WalletJournalReference struct {
	CorporationID int32              `json:"corporation_id"`
	Division      int32              `json:"division"`
	JournalID     int64              `json:"journal_id"`
	ReferenceType string             `json:"reference_type"`
	ReferenceID   string             `json:"reference_id"`
	Status        int16              `json:"status"`
	Amount        pgtype.Numeric     `json:"amount"`
	Note          *string            `json:"note"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type War struct {
	WarID                  int32              `json:"war_id"`
	Declared               pgtype.Timestamptz `json:"declared"`
	Started                pgtype.Timestamptz `json:"started"`
	Finished               pgtype.Timestamptz `json:"finished"`
	Retracted              pgtype.Timestamptz `json:"retracted"`
	Mutual                 *bool              `json:"mutual"`
	OpenForAllies          *bool              `json:"open_for_allies"`
	AggressorAllianceID    *int32             `json:"aggressor_alliance_id"`
	AggressorCorporationID *int32             `json:"aggressor_corporation_id"`
	AggressorIskDestroyed  *float64           `json:"aggressor_isk_destroyed"`
	AggressorShipsKilled   *int32             `json:"aggressor_ships_killed"`
	DefenderAllianceID     *int32             `json:"defender_alliance_id"`
	DefenderCorporationID  *int32             `json:"defender_corporation_id"`
	DefenderIskDestroyed   *float64           `json:"defender_isk_destroyed"`
	DefenderShipsKilled    *int32             `json:"defender_ships_killed"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type WarAlly struct {
	ID            int32  `json:"id"`
	WarID         int32  `json:"war_id"`
	AllianceID    *int32 `json:"alliance_id"`
	CorporationID *int32 `json:"corporation_id"`
}

type WarInteraction struct {
	WarID            int32              `json:"war_id"`
	Side             int16              `json:"side"`
	Category         int16              `json:"category"`
	TargetType       int16              `json:"target_type"`
	TargetID         int32              `json:"target_id"`
	Count            *int32             `json:"count"`
	IskValue         *float64           `json:"isk_value"`
	LastKillmailID   *int32             `json:"last_killmail_id"`
	LastKillmailTime pgtype.Timestamptz `json:"last_killmail_time"`
}
